name: hippo
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0
  google_fonts: ^2.0.0
  flutter_screenutil: ^5.0.0-nullsafety.11
  r_dart_library: 0.4.0-nullsafety.0
  flutter_rating_bar: ^4.0.0
  percent_indicator: ^3.3.0-nullsafety.1
  flutter_switch: ^0.3.1

  # GETX STATE MANAGEMENT
  get: ^4.3.6
  get_storage: ^2.0.2

  # UTILITIES
#  device_info: ^2.0.1
  package_info: ^2.0.0
  url_launcher: ^6.0.4

  cached_network_image: ^3.0.0
  otp_text_field: ^1.1.1
  image_picker: ^0.8.0

  carousel_slider: ^4.0.0-nullsafety.0
  share_plus: ^2.1.4
  auto_size_text: ^3.0.0
  sticky_headers: ^0.2.0
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  customizable_space_bar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/demo/
    - assets/images/dashboard_bg.svg
    - assets/images/dashboard_logo.png
    - assets/images/ic_caregiver.svg
  fonts:
    - family: Arien
      fonts:
        - asset: assets/fonts/Montserrat_Regular.ttf
          style: normal
        - asset: assets/fonts/Montserrat_Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat_Regular.ttf
          style: italic
flutter_intl:
  enabled: true
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
    - assets/images
  fonts:
    - assets/fonts
